public class WrappingTests {
  public AbsurdlyLongClassNameDesignedSpecificallyToExplodeLineWrappingLogic
    shortVar;
  public ShortType
    extremelyLongVariableNameThatJustKeepsGoingAndGoingForNoGoodReasonWhatsoeverField;
  public Map<RidiculouslyVerboseAndOverlyDescriptiveMapKeyTypeName, ShortValue>
    mapWithLongKeyField;
  public Map<ShortKey,
    IncrediblyAndUnnecessarilyLongMapValueTypeNameDesignedToWrap>
    mapWithLongValueField;
  public Map<OuterKeyThatIsSoLongItAloneBreaksTheLineWrappingRules,
    Map<ShortInnerKey, ShortInnerValue>>
    nestedMapWithLongOuterKeyField;

  public void parentMethod() {
    AbsurdlyLongClassNameDesignedSpecificallyToExplodeLineWrappingLogic
      shortMethodVar;
    ShortType
      extremelyLongVariableNameThatJustKeepsGoingAndGoingForNoGoodReasonWhatsoeverMethodVar;
    Map<RidiculouslyVerboseAndOverlyDescriptiveMapKeyTypeName, ShortValue>
      mapWithLongKeyMethodVar;
    Map<ShortKey, IncrediblyAndUnnecessarilyLongMapValueTypeNameDesignedToWrap>
      mapWithLongValueMethodVar;
    Map<OuterKeyThatIsSoLongItAloneBreaksTheLineWrappingRules,
      Map<ShortInnerKey, ShortInnerValue>>
      nestedMapWithLongOuterKeyMethodVar;
  }

  public class InnerWrappingTests {
    public AbsurdlyLongClassNameDesignedSpecificallyToExplodeLineWrappingLogic
      shortInnerFieldVar;
    public ShortType
      extremelyLongVariableNameThatJustKeepsGoingAndGoingForNoGoodReasonWhatsoeverInnerField;
    public Map<RidiculouslyVerboseAndOverlyDescriptiveMapKeyTypeName,
      ShortValue>
      mapWithLongKeyInnerField;
    public Map<ShortKey,
      IncrediblyAndUnnecessarilyLongMapValueTypeNameDesignedToWrap>
      mapWithLongValueInnerField;
    public Map<OuterKeyThatIsSoLongItAloneBreaksTheLineWrappingRules,
      Map<ShortInnerKey, ShortInnerValue>>
      nestedMapWithLongOuterKeyInnerField;

    public void innerMethod() {
      AbsurdlyLongClassNameDesignedSpecificallyToExplodeLineWrappingLogic
        shortInnerMethodVar;
      ShortType
        extremelyLongVariableNameThatJustKeepsGoingAndGoingForNoGoodReasonWhatsoeverInnerMethodVar;
      Map<RidiculouslyVerboseAndOverlyDescriptiveMapKeyTypeName, ShortValue>
        mapWithLongKeyInnerMethodVar;
      Map<ShortKey,
        IncrediblyAndUnnecessarilyLongMapValueTypeNameDesignedToWrap>
        mapWithLongValueInnerMethodVar;
      Map<OuterKeyThatIsSoLongItAloneBreaksTheLineWrappingRules,
        Map<ShortInnerKey, ShortInnerValue>>
        nestedMapWithLongOuterKeyInnerMethodVar;
    }
  }
}
